// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { ElegantRoute } from '@elegant-router/types';

export const autoRoutes: ElegantRoute[] = [
  {
    path: '/403',
    component: 'layout.blank',
    children: [
      {
        name: '403',
        path: '',
        component: 'view.403',
        meta: {
          title: '403',
          i18nKey: 'route.403',
          constant: true
        }
      }
    ]
  },
  {
    path: '/404',
    component: 'layout.blank',
    children: [
      {
        name: '404',
        path: '',
        component: 'view.404',
        meta: {
          title: '404',
          i18nKey: 'route.404',
          constant: true
        }
      }
    ]
  },
  {
    path: '/500',
    component: 'layout.blank',
    children: [
      {
        name: '500',
        path: '',
        component: 'view.500',
        meta: {
          title: '500',
          i18nKey: 'route.500',
          constant: true
        }
      }
    ]
  },
  {
    path: '/home',
    component: 'layout.base',
    children: [
      {
        name: 'home',
        path: '',
        component: 'view.home',
        meta: {
          title: 'home',
          i18nKey: 'route.home',
          icon: 'mdi:monitor-dashboard',
          requiresAuth: true
        }
      }
    ]
  },
  {
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank',
    children: [
      {
        name: 'login',
        path: '',
        component: 'view.login',
        meta: {
          title: 'login',
          i18nKey: 'route.login',
          constant: true
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    redirect: {
      name: 'multi-menu_first'
    },
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      requiresAuth: true
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        redirect: {
          name: 'multi-menu_first_child'
        },
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          requiresAuth: true
        }
      },
      {
        name: 'multi-menu_first_child',
        path: '/multi-menu/first/child',
        component: 'view.multi-menu_first_child',
        meta: {
          title: 'multi-menu_first_child',
          i18nKey: 'route.multi-menu_first_child',
          requiresAuth: true
        }
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        redirect: {
          name: 'multi-menu_second_child'
        },
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          requiresAuth: true
        }
      },
      {
        name: 'multi-menu_second_child',
        path: '/multi-menu/second/child',
        redirect: {
          name: 'multi-menu_second_child_home'
        },
        meta: {
          title: 'multi-menu_second_child',
          i18nKey: 'route.multi-menu_second_child',
          requiresAuth: true
        }
      },
      {
        name: 'multi-menu_second_child_home',
        path: '/multi-menu/second/child/home',
        component: 'view.multi-menu_second_child_home',
        meta: {
          title: 'multi-menu_second_child_home',
          i18nKey: 'route.multi-menu_second_child_home',
          requiresAuth: true
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    redirect: {
      name: 'user_detail'
    },
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'ic:round-manage-accounts',
      requiresAuth: true
    },
    children: [
      {
        name: 'user_detail',
        path: '/user/detail/:id',
        component: 'view.user_detail',
        meta: {
          title: 'user_detail',
          i18nKey: 'route.user_detail',
          icon: 'ic:round-account-box',
          requiresAuth: true
        }
      },
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: 'user_list',
          i18nKey: 'route.user_list',
          icon: 'mdi:table-large',
          requiresAuth: true
        }
      }
    ]
  },
  {
    path: '/user-center',
    component: 'layout.base',
    children: [
      {
        name: 'user-center',
        path: '',
        component: 'view.user-center',
        meta: {
          title: 'user-center',
          i18nKey: 'route.user-center',
          requiresAuth: true,
          hideInMenu: true
        }
      }
    ]
  }
];
